from crewai import Agent, Task


def create_analysis_task(agent: Agent, symbol: str) -> Task:
    """Task 1 – Fundamental + Technical analysis assigned to the Stock Analyst agent."""
    return Task(
        name="stock_fundamental_technical_analysis",
        description=(
            f"Conduct a comprehensive fundamental and technical analysis of {symbol}.\n\n"
            "STEP 1 – FUNDAMENTAL ANALYSIS: call the 'Get Stock Fundamental Data' tool.\n"
            "Extract and report every single field the tool returns:\n"
            "  • Company profile: name, exchange, sector, industry, country, currency\n"
            "  • Current price, previous close, open, day high/low, 52-week high/low\n"
            "  • Market cap, enterprise value, shares outstanding\n"
            "  • Valuation: P/E TTM, P/E Forward, PEG, P/B, P/S TTM, EV/EBITDA\n"
            "  • EPS TTM and Forward\n"
            "  • Revenue TTM, revenue growth YoY, earnings growth YoY\n"
            "  • Gross margin, operating margin, net profit margin, EBITDA\n"
            "  • ROE, ROA, total cash, total debt, debt/equity, current ratio, free cash flow\n"
            "  • Dividend yield, payout ratio, beta, short ratio\n"
            "  • Analyst target mean/low/high, recommendation, number of analysts\n\n"
            "STEP 2 – TECHNICAL ANALYSIS: call the 'Get Technical Analysis Indicators' tool.\n"
            "Extract and report every single field the tool returns:\n"
            "  • Current price, prev close, daily change and daily change %\n"
            "  • SMA-20, SMA-50, SMA-200, EMA-12, EMA-26 — whether price is above/below each\n"
            "  • Golden Cross / Death Cross status\n"
            "  • RSI(14) exact value + overbought/oversold/neutral signal\n"
            "  • MACD, MACD signal line, MACD histogram, crossover direction\n"
            "  • Bollinger Bands upper/middle/lower, current band position\n"
            "  • Stochastic %K and %D\n"
            "  • ATR(14) exact value\n"
            "  • Current volume, volume SMA-20, volume ratio, volume signal\n"
            "  • 1W, 1M, 3M, 6M, YTD returns\n"
            "  • 52-week high/low and % distance from each\n"
            "  • Overall trend assessment from tool\n\n"
            "CRITICAL RULES:\n"
            "  1. Copy EXACT numeric values from tool output — never round, estimate, or omit any field.\n"
            "  2. Format all data as markdown tables (| Metric | Value | Signal |).\n"
            "  3. Every section must start with the exact heading shown in the expected output."
        ),
        expected_output=(
            "A structured, data-rich report with the following sections and markdown tables.\n"
            "Replace every placeholder with the EXACT value from the tool — no estimates.\n\n"
            "## FUNDAMENTAL ANALYSIS\n\n"
            "### Company Profile\n"
            "| Field | Value |\n"
            "|-------|-------|\n"
            "| Company Name | [exact] |\n"
            "| Ticker / Exchange | [exact] |\n"
            "| Sector / Industry | [exact] |\n"
            "| Country / Currency | [exact] |\n\n"
            "[2-sentence business summary from the tool]\n\n"
            "### Price & Size\n"
            "| Metric | Value |\n"
            "|--------|-------|\n"
            "| Current Price | [exact] |\n"
            "| Previous Close | [exact] |\n"
            "| Day Range | [low] – [high] |\n"
            "| 52-Week Range | [low] – [high] |\n"
            "| Market Cap | [exact] |\n"
            "| Enterprise Value | [exact] |\n"
            "| Beta | [exact] |\n\n"
            "### Valuation Ratios\n"
            "| Metric | Value | Context |\n"
            "|--------|-------|---------|\n"
            "| P/E Ratio (TTM) | [exact] | Over/Under/Fair valued vs sector |\n"
            "| P/E Ratio (Forward) | [exact] | |\n"
            "| PEG Ratio | [exact] | <1 undervalued / >2 expensive |\n"
            "| Price / Book | [exact] | |\n"
            "| Price / Sales (TTM) | [exact] | |\n"
            "| EV / EBITDA | [exact] | |\n"
            "| EPS (TTM) | [exact] | |\n"
            "| EPS (Forward) | [exact] | |\n\n"
            "### Financial Performance\n"
            "| Metric | Value | Assessment |\n"
            "|--------|-------|------------|\n"
            "| Revenue (TTM) | [exact] | |\n"
            "| Revenue Growth YoY | [exact] | Strong/Moderate/Weak |\n"
            "| Earnings Growth YoY | [exact] | |\n"
            "| Gross Margin | [exact] | |\n"
            "| Operating Margin | [exact] | |\n"
            "| Net Profit Margin | [exact] | |\n"
            "| EBITDA | [exact] | |\n"
            "| ROE | [exact] | |\n"
            "| ROA | [exact] | |\n"
            "| Free Cash Flow | [exact] | |\n\n"
            "### Balance Sheet Health\n"
            "| Metric | Value | Signal |\n"
            "|--------|-------|--------|\n"
            "| Total Cash | [exact] | |\n"
            "| Total Debt | [exact] | |\n"
            "| Debt / Equity | [exact] | Low (<1) / Moderate / High |\n"
            "| Current Ratio | [exact] | Healthy (>1.5) / Caution |\n"
            "| Dividend Yield | [exact] | |\n"
            "| Payout Ratio | [exact] | |\n\n"
            "### Analyst Consensus\n"
            "| Metric | Value |\n"
            "|--------|-------|\n"
            "| Recommendation | [exact] |\n"
            "| Price Target (Mean) | [exact] |\n"
            "| Target Range | [low] – [high] |\n"
            "| Number of Analysts | [exact] |\n\n"
            "**Fundamental Score: [X] / 10** — [2-sentence rationale citing specific metrics above]\n\n"
            "---\n\n"
            "## TECHNICAL ANALYSIS\n\n"
            "### Trend & Moving Averages\n"
            "| Indicator | Value | Signal |\n"
            "|-----------|-------|--------|\n"
            "| Current Price | [exact] | |\n"
            "| SMA-20 | [exact] | Price [above/below] — [Bullish/Bearish] |\n"
            "| SMA-50 | [exact] | Price [above/below] — [Bullish/Bearish] |\n"
            "| SMA-200 | [exact] | Price [above/below] — [Bullish/Bearish] |\n"
            "| EMA-12 | [exact] | |\n"
            "| EMA-26 | [exact] | |\n"
            "| Golden/Death Cross | [Yes/No] | [Bullish/Bearish] |\n\n"
            "### Momentum Indicators\n"
            "| Indicator | Value | Signal |\n"
            "|-----------|-------|--------|\n"
            "| RSI (14) | [exact] | [Overbought >70 / Oversold <30 / Neutral] |\n"
            "| MACD | [exact] | [Bullish/Bearish] crossover |\n"
            "| MACD Signal Line | [exact] | |\n"
            "| MACD Histogram | [exact] | |\n"
            "| Stochastic %K | [exact] | |\n"
            "| Stochastic %D | [exact] | |\n\n"
            "### Volatility & Volume\n"
            "| Indicator | Value | Signal |\n"
            "|-----------|-------|--------|\n"
            "| Bollinger Band Upper | [exact] | |\n"
            "| Bollinger Band Middle | [exact] | |\n"
            "| Bollinger Band Lower | [exact] | |\n"
            "| Band Position | [exact] | Above Upper / Within / Below Lower |\n"
            "| ATR (14) | [exact] | |\n"
            "| Current Volume | [exact] | |\n"
            "| Volume SMA-20 | [exact] | |\n"
            "| Volume Ratio | [exact]x | [Above/Below] average |\n\n"
            "### Period Returns & 52-Week Range\n"
            "| Period | Return | Context |\n"
            "|--------|--------|---------|\n"
            "| 1 Week | [exact] | |\n"
            "| 1 Month | [exact] | |\n"
            "| 3 Months | [exact] | |\n"
            "| 6 Months | [exact] | |\n"
            "| YTD | [exact] | |\n"
            "| % from 52W High | [exact] | |\n"
            "| % from 52W Low | [exact] | |\n\n"
            "**Overall Trend Assessment:** [exact value from tool]\n\n"
            "**Technical Score: [X] / 10** — [2-sentence rationale citing specific indicators above]\n\n"
            "---\n\n"
            "## PRELIMINARY ASSESSMENT\n\n"
            "[One concise paragraph combining fundamental and technical signals, "
            "identifying 2–3 key strengths and 2–3 key risks, "
            "and stating an overall preliminary score out of 10.]"
        ),
        agent=agent,
    )
