from crewai import Agent, Task


def create_report_task(
    agent: Agent,
    analysis_task: Task,
    news_task: Task,
    symbol: str,
    session_id: str,
) -> Task:
    """Task 3 – Comprehensive investment report assigned to the Investment Strategist agent."""
    return Task(
        name="investment_report_generation",
        description=(
            f"Write a comprehensive, institutional-grade investment report for {symbol} "
            f"using the EXACT data from Agent 1 (fundamental + technical analysis) and "
            f"Agent 2 (news + sentiment) provided in your context.\n\n"
            "══ CRITICAL DATA RULES ══\n"
            "• Use the EXACT current price, market cap, P/E, EPS, margins, RSI, MACD, "
            "  SMA values and all other metrics from the context — do NOT invent, estimate, "
            "  approximate, or use placeholder values like '[X]' or 'approximately'.\n"
            "• Use the EXACT company name, sector, and analyst consensus from the context.\n"
            "• Every section that references financial data must present it in a markdown table.\n"
            "• Price targets must be derived from the analyst consensus data in the context, "
            "  not invented.\n\n"
            "REPORT STRUCTURE — include ALL 8 sections:\n\n"
            "1. EXECUTIVE SUMMARY\n"
            "   • Company name, ticker symbol, exchange, sector — exact from context\n"
            "   • Current market price — exact from context\n"
            "   • Final recommendation: **BUY** / **HOLD** / **SELL** on its own line\n"
            "   • 12-month price target (base case) derived from analyst consensus in context\n"
            "   • Upside/downside % from current price\n"
            "   • 3-sentence investment thesis\n\n"
            "2. COMPANY OVERVIEW\n"
            "   • Business description using the business summary from context\n"
            "   • Key revenue drivers and competitive moat\n"
            "   • Market position and industry context\n\n"
            "3. FUNDAMENTAL ANALYSIS SUMMARY\n"
            "   • Highlight the top 8 valuation and financial metrics from the context in a table\n"
            "   • Balance sheet assessment (cash vs debt, current ratio, free cash flow)\n"
            "   • Growth trajectory (revenue growth, earnings growth, margin trends)\n"
            "   • Fundamental score from context with your commentary\n\n"
            "4. TECHNICAL ANALYSIS SUMMARY\n"
            "   • Current trend narrative using SMA-20/50/200 values from context\n"
            "   • Key support level (use SMA-50 or SMA-200 from context)\n"
            "   • Key resistance level (use 52-week high from context)\n"
            "   • Momentum summary: RSI, MACD, Stochastic — exact values from context\n"
            "   • Suggested entry zone and stop-loss based on ATR from context\n"
            "   • Technical score from context with your commentary\n\n"
            "5. NEWS & SENTIMENT ANALYSIS\n"
            "   • Top 3 most market-impactful news stories from Agent 2 context\n"
            "   • Corporate catalysts (positive and negative) — dates from context\n"
            "   • Analyst activity summary from context\n"
            "   • News sentiment score from context\n\n"
            "6. INVESTMENT RECOMMENDATION\n"
            "   • Clear **BUY / HOLD / SELL** on its own line\n"
            "   • Bull Case: exactly 3 data-backed reasons (use metrics from context)\n"
            "   • Bear Case: exactly 3 data-backed risks\n"
            "   • Price target table: Base / Bull / Bear scenarios with % upside/downside\n"
            "   • Position sizing: Aggressive / Moderate / Conservative recommendation\n\n"
            "7. RISK FACTORS\n"
            "   • Exactly 5 risks in a table with Severity (High/Medium/Low) and mitigation\n\n"
            "8. CONCLUSION\n"
            "   • One concise closing paragraph tying all themes together\n"
            "   • Standard investment disclaimer"
        ),
        expected_output=(
            "A complete, professional institutional investment report with all 8 sections.\n"
            "All financial data must be presented in markdown tables using EXACT values from context.\n\n"
            "## EXECUTIVE SUMMARY\n"
            "| Field | Details |\n"
            "|-------|---------|\n"
            "| Company | [Company name] ([ticker]) |\n"
            "| Exchange | [exact] |\n"
            "| Sector | [exact sector] |\n"
            "| Current Price | [EXACT price from context] |\n"
            "| Market Cap | [exact] |\n"
            "| **Recommendation** | **BUY / HOLD / SELL** |\n"
            "| 12-Month Price Target | [analyst mean target] ([upside/downside]%) |\n"
            "| Risk / Reward | [brief 1-line assessment] |\n\n"
            "**Investment Thesis:** [3-sentence thesis using specific data points — price, P/E, growth, catalyst]\n\n"
            "## COMPANY OVERVIEW\n"
            "[Business description paragraph from context] [Competitive positioning paragraph]\n\n"
            "## FUNDAMENTAL ANALYSIS SUMMARY\n"
            "| Metric | Value | Assessment |\n"
            "|--------|-------|------------|\n"
            "| Current Price | [exact from context] | |\n"
            "| P/E Ratio (TTM) | [exact from context] | Over/Under/Fair valued |\n"
            "| P/E Ratio (Forward) | [exact from context] | |\n"
            "| Revenue (TTM) | [exact from context] | |\n"
            "| Net Profit Margin | [exact from context] | Strong/Moderate/Weak |\n"
            "| ROE | [exact from context] | |\n"
            "| Debt / Equity | [exact from context] | Low/Moderate/High |\n"
            "| Analyst Target (Mean) | [exact from context] | |\n"
            "[Balance sheet and growth commentary paragraph] [Fundamental Score: X/10]\n\n"
            "## TECHNICAL ANALYSIS SUMMARY\n"
            "| Indicator | Value | Signal |\n"
            "|-----------|-------|--------|\n"
            "| Current Price | [exact from context] | |\n"
            "| SMA-50 | [exact from context] | [above/below] |\n"
            "| SMA-200 | [exact from context] | [above/below] |\n"
            "| RSI (14) | [exact from context] | [signal] |\n"
            "| MACD | [exact from context] | [signal] |\n"
            "| Volume Ratio | [exact from context] | [above/below avg] |\n"
            "Support: [SMA-50 or SMA-200 value from context] | "
            "Resistance: [52W high from context]\n"
            "Entry Zone: [derived from current price ± ATR] | Stop-Loss: [current price – 1.5×ATR]\n"
            "[Technical Score: X/10 with commentary]\n\n"
            "## NEWS & SENTIMENT ANALYSIS\n\n"
            "**Top Market-Moving Stories:**\n"
            "• **[Headline 1]** ([date], [source]) — [1-sentence impact summary] — 🟢 Positive / 🔴 Negative / ⚪ Neutral\n"
            "• **[Headline 2]** ([date], [source]) — [1-sentence impact summary] — [impact]\n"
            "• **[Headline 3]** ([date], [source]) — [1-sentence impact summary] — [impact]\n\n"
            "**Corporate Catalysts:**\n"
            "• ✅ [Positive catalyst 1 with date and brief implication]\n"
            "• ✅ [Positive catalyst 2 with date and brief implication]\n"
            "• ⚠️ [Negative / risk catalyst with date and brief implication]\n\n"
            "**Analyst Activity:**\n"
            "• [Firm 1]: [Upgrade/Downgrade/Reiterate] — Target [old price] → [new price] ([date])\n"
            "• [Firm 2]: [action] — [brief rationale] ([date])\n\n"
            "**Macro & Sector Factors:**\n"
            "• [Macro factor 1 and its directional impact on the stock]\n"
            "• [Macro factor 2 and its directional impact]\n"
            "• [Sector trend and relevance]\n\n"
            "**News Sentiment Score: [exact score from context] / 10** — [2-sentence justification]\n\n"
            "## INVESTMENT RECOMMENDATION\n"
            "**[BUY / HOLD / SELL]**\n\n"
            "**Bull Case:** [3 numbered, data-backed reasons]\n"
            "**Bear Case:** [3 numbered, data-backed risks]\n\n"
            "| Scenario | Price Target | Upside/Downside | Key Assumption |\n"
            "|----------|-------------|-----------------|----------------|\n"
            "| Base Case | [analyst mean from context] | [%] | [assumption] |\n"
            "| Bull Case | [analyst high from context] | [%] | [assumption] |\n"
            "| Bear Case | [analyst low from context] | [%] | [assumption] |\n\n"
            "Position Sizing: [Aggressive/Moderate/Conservative] — [1-sentence rationale]\n\n"
            "## RISK FACTORS\n"
            "| # | Risk | Severity | Mitigation |\n"
            "|---|------|----------|------------|\n"
            "| 1 | [risk] | High | [mitigation] |\n"
            "| 2 | [risk] | Medium | [mitigation] |\n"
            "| 3 | [risk] | Medium | [mitigation] |\n"
            "| 4 | [risk] | Low | [mitigation] |\n"
            "| 5 | [risk] | Low | [mitigation] |\n\n"
            "## CONCLUSION\n"
            "[One paragraph closing summary with key takeaways and final stance]\n\n"
            "*Disclaimer: This report is generated by an AI system for informational purposes only "
            "and does not constitute financial advice. Always conduct your own research and consult "
            "a qualified financial advisor before making investment decisions.*"
        ),
        agent=agent,
        context=[analysis_task, news_task],
    )
